# Application
spring.application.name=feeder
server.port=8080
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
logging.file.path=logs

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration