spring.application.name=api
server.port=8090

# Altera a estrutura da tabela caso a entidade tenha mudanças
spring.jpa.hibernate.ddl-auto=update

# Acessa ao banco de dados
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/

# Usuario ao banco de dados
spring.datasource.username=

# Senha ao banco de dados
spring.datasource.password=

# Acessa ao banco de dados
spring.datasource.drive-class-name=com.mysql.cj.jdbc.Driver
